// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCp0XVESaWl5FRSSVfw6ufoD4zmiZAsf0',
    appId: '1:927285317965:web:7b7330ff411f5b33eb6704',
    messagingSenderId: '927285317965',
    projectId: 'weather-app-f9c34',
    authDomain: 'weather-app-f9c34.firebaseapp.com',
    storageBucket: 'weather-app-f9c34.appspot.com',
    measurementId: 'G-QW3RJHMZHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuVodZVuLwF31a2EVFhYst2b0Oi_672wE',
    appId: '1:927285317965:android:494a7782ce143548eb6704',
    messagingSenderId: '927285317965',
    projectId: 'weather-app-f9c34',
    storageBucket: 'weather-app-f9c34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEiNdhv46tvl8c18Oe-koDWeO510Wq0PY',
    appId: '1:927285317965:ios:ecc40ed6c631b482eb6704',
    messagingSenderId: '927285317965',
    projectId: 'weather-app-f9c34',
    storageBucket: 'weather-app-f9c34.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEiNdhv46tvl8c18Oe-koDWeO510Wq0PY',
    appId: '1:927285317965:ios:e7d7684afded1344eb6704',
    messagingSenderId: '927285317965',
    projectId: 'weather-app-f9c34',
    storageBucket: 'weather-app-f9c34.appspot.com',
    iosBundleId: 'com.example.weatherApp.RunnerTests',
  );
}
